style: auto-format docker/Dockerfile with prettier

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -17,14 +17,14 @@ ENV CI=true
 COPY --from=node /root/.nvm/versions/node/$NODE_VERSION/ /opt/node/
 ENV PATH=/opt/node/bin:$PATH
 RUN apt-get update && \
- apt-get install -y --no-install-recommends build-essential python3 jq && \
- rm -rf /var/lib/apt/lists/*
+  apt-get install -y --no-install-recommends build-essential python3 jq && \
+  rm -rf /var/lib/apt/lists/*
 
 # Generate a toolchains.xml
 COPY docker/toolchains-template.xml /tmp/toolchains-template.xml
 RUN mkdir -p /root/.m2 \
- && cat /tmp/toolchains-template.xml \
- | xargs -0 -I "{}" printf "{}" "$JAVA_VERSION_SHORT" "$JAVA_HOME" > /root/.m2/toolchains.xml
+  && cat /tmp/toolchains-template.xml \
+  | xargs -0 -I "{}" printf "{}" "$JAVA_VERSION_SHORT" "$JAVA_HOME" > /root/.m2/toolchains.xml
 
 
 FROM adoptopenjdk:${JAVA_VERSION_SHORT}-jre-hotspot-focal AS test-runner-base
@@ -36,8 +36,8 @@ RUN adduser --disabled-password --gecos '' ci
 # procps contains pgrep which is needed by integration tests. Python is used by node-gyp when
 # building native node modules.
 RUN apt-get update && \
- apt-get install -y --no-install-recommends build-essential procps python3 && \
- rm -rf /var/lib/apt/lists/*
+  apt-get install -y --no-install-recommends build-essential procps python3 && \
+  rm -rf /var/lib/apt/lists/*
 
 RUN echo "set -euxo pipefail" >> ~/.bashrc
 
@@ -47,29 +47,29 @@ USER ci
 
 FROM test-runner-base AS test-runner
 CMD echo "Node version:" && node --version && \
-    echo "Java version:" && java -version && \
-    echo "Copying project files..." && \
-    cd /project-files && \
-    find . \( -name .git -o -name build -o -path ./java/target -o \
-              -name .idea -o -name node_modules -o -name test-reports \) -prune -o -type f \
-      -exec install -pDT "{}" "/code/{}" \; && \
-    cd /code && \
-    ( test -n "$(find java/target/jars -name '*.jar' 2>/dev/null)" \
-      || ( echo 'Error: No jars found at java/target/jars, `docker-compose run build-package` needs to be run to create them.' \
-           && exit 1 ) ) && \
-    npm ci && \
-    npm run test
+  echo "Java version:" && java -version && \
+  echo "Copying project files..." && \
+  cd /project-files && \
+  find . \( -name .git -o -name build -o -path ./java/target -o \
+  -name .idea -o -name node_modules -o -name test-reports \) -prune -o -type f \
+  -exec install -pDT "{}" "/code/{}" \; && \
+  cd /code && \
+  ( test -n "$(find java/target/jars -name '*.jar' 2>/dev/null)" \
+  || ( echo 'Error: No jars found at java/target/jars, `docker-compose run build-package` needs to be run to create them.' \
+  && exit 1 ) ) && \
+  npm ci && \
+  npm run test
 
 
 FROM test-runner-base AS integration-test-runner
 CMD echo "Node version:" && node --version && \
-    echo "Java version:" && java -version && \
-    echo "Copying project files..." && \
-    cd /project-files && \
-    find ./integration-test ./examples \( -name node_modules -o -name test-reports \) -prune -o -type f \
-          -exec install -pDT "{}" "/code/{}" \; && \
-    cd /code && \
-    echo "\nRunning integration tests..." && \
-    integration-test/run-all.sh && \
-    echo "\nRunning examples..." && \
-    examples/run-all.sh
+  echo "Java version:" && java -version && \
+  echo "Copying project files..." && \
+  cd /project-files && \
+  find ./integration-test ./examples \( -name node_modules -o -name test-reports \) -prune -o -type f \
+  -exec install -pDT "{}" "/code/{}" \; && \
+  cd /code && \
+  echo "\nRunning integration tests..." && \
+  integration-test/run-all.sh && \
+  echo "\nRunning examples..." && \
+  examples/run-all.sh
